/**
 * Created by Garie on 14/5/2016.
 */
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const DISPLAY_FOOD_DETAILS = 'DISPLAY_FOOD_DETAILS';
export const DISPLAY_SELECTED_NUTRIENTS = 'DISPLAY_SELECTED_NUTRIENTS';
export const BOOKMARK_SELECTED_FOOD = 'BOOKMARK_SELECTED_FOOD';
export const DELETE_SELECTED_BOOKMARK = 'DELETE_SELECTED_BOOKMARK';
export const DELETE_ALL_BOOKMARKS = 'DELETE_ALL_BOOKMARKS';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';